filter:
    excluded_paths:
        - "**/__tests__/"
        - "*.min.js"
build:
    tests:
        override:
            -
                command: 'npm run coverage'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
