version: "3"
services:
    mongodb:
        image: mongo
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db/:/data/db
        ports:
            - 27017:27017
        command: mongod

    express:
        build:
            context: .
            dockerfile: docker/Dockerfile-express
        environment:
            - DBWEBB_PORT=3000
            - DBWEBB_DSN=mongodb://mongodb:27017/redovisa
        links:
            - mongodb
        volumes:
            - ./:/app/
            - /app/node_modules
        ports:
            - "3000:3000"
        command: "npm start"


    node_9_alpine:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-9-alpine
        volumes:
            - ./:/app
        ports:
            - "3090:3000"

    node_8_alpine:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-8-alpine
        volumes:
            - ./:/app
        ports:
            - "3080:3000"

    node_7_alpine:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-7-alpine
        volumes:
            - ./:/app
        ports:
            - "3070:3000"
